name: dist-windows
on: [push]
jobs:
  dist:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Poetry
        shell: powershell
        run: (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
      - name: Install dependencies
        run: poetry install
      - name: Check formatting with Black
        run: poetry run black --check .
