name: dist-windows
on: [push]
jobs:
  dist:
    runs-on: windows-latest
    env:
      POETRY_HOME: C:/poetry
      PIP_DISABLE_PIP_VERSION_CHECK: yes
      PIP_NO_CACHE_DIR: yes
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: Show Poetry version
        shell: powershell
        run: C:\poetry\bin\poetry.bat version
      - name: Install dependencies
        shell: powershell
        run: C:/poetry/bin/poetry.bat install
      #- name: Check formatting with Black
      #  shell: powershell
      #  run: C:/poetry/bin/poetry.bat run black --check .
      - name: Run PyInstaller
        shell: powershell
        run: C:/poetry/bin/poetry.bat run pyinstaller -w --onefile pdf_crypt.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf_crypt.exe
          path: dist/pdf_crypt.exe
